server:
  port: 8080


spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.21.0.2:3306/palette?useUniCode=yes&characterEncoding=UTF-8
    username: palette
    password: 'haru0220'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # JPA Properties
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      jdbc:
        time_zone: Asia/Seoul
    open-in-view: false

  # Redis
  redis:
    host: 172.21.0.3
    port: 6379
    password: 'haru0220'

  # application-auth, s3
  profiles:
    include:
      - auth
      - s3
