server:
  port: 8090

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b303.p.ssafy.io:3306/palette_auth?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: palette
    password: haru0220

  # JPA Properties
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false

  # application-auth
  profiles:
    includ e: auth