spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 685bbaa521fca86f73dae4e8dcf4a0fa
            client-secret: xoobzG5gRBkyZcpUMXQemL8W4FoaOa5t
            redirect-uri: http://localhost:8090/oauth2/login/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_image
              - profile_nickname
              - gender
              - age_range
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# JWT
jwt:
  header: Authorization
  secret: U1NBRlkgSGFydSBQYWxldHRlIDAyMjAg6ri47IOB7JqxIOq5gOyGjOycpCDquYDssL3qsrgg7ISc7JiI7KeAIOycoOyngOyXsCDsnoTshLHruYg=
  token-validity-in-seconds: 3600